services:
  redis:
    image: redis
    container_name: one-redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - one
    restart: on-failure
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data

  mongo:
    image: mongo
    container_name: one-mongo
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo/data:/data/db
    networks:
      - one

  ollama:
    image: alpine/ollama
    container_name: ollama
    restart: always
    ports:
      - 11434:11434
    volumes:
      - ~/.ollama:/root/.ollama
    networks:
      - one

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - ./rabbitmq/rabbitmq:/var/lib/rabbitmq # 持久化数据
      - ./rabbitmq/log:/var/log/rabbitmq # 持久化日志
    networks:
      - one

  elasticsearch:
    container_name: es01
    image: elasticsearch:8.12.2
    restart: unless-stopped
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "TZ=Asia/Shanghai"
      - "discovery.type=single-node"
      - "ELASTIC_PASSWORD=123456"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      # - ./config:/usr/share/elasticsearch/config
      - ./data:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
    networks:
      - one
  kibana:
    container_name: kibana01
    image: kibana:8.12.2
    restart: unless-stopped
    environment:
      - "TZ=Asia/Shanghai"
      - "I18N_LOCALE=zh-CN"
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "ELASTICSEARCH_USERNAME=test"
      - "ELASTICSEARCH_PASSWORD=123456"
    ports:
      - "5601:5601"
        #volumes:
        #- ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - one
    depends_on:
      - elasticsearch

networks:
  one:
    driver: bridge
    external: true
