services:
  redis:
    image: redis
    container_name: one-redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - one
    restart: on-failure
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data

  mongo:
    image: mongo
    container_name: one-mongo
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo/data:/data/db
    networks:
      - one

  ollama:
    image: alpine/ollama
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ~/.ollama:/root/.ollama
    networks:
      - default

networks:
  one:
    driver: bridge
