include:
  - ./docker-compose-base.yml

services:
  # web:
  #   # build:
  #   #   context: ../web/ui
  #   #   dockerfile: Dockerfile
  #   # image: one-ui
  #   build:
  #     context: ../web/ui/
  #     dockerfile: Dockerfile
  #   container_name: one-ui
  #   ports:
  #     - "${UI_PORT}:3000"
  #   volumes:
  #     - ../web/ui/docker/pm2.json:/app/pm2.json
  #     - ../web/ui/docker/entrypoint.sh:/app/entrypoint.sh
  #   restart: on-failure
  #   networks:
  #     - one
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  worker:
    image: one-server
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - redis
    container_name: one-worker
    volumes:
      - ./worker.sh:/app/worker.sh
    restart: on-failure
    entrypoint: ["/app/worker.sh"]
    networks:
      - one
    extra_hosts:
      - "host.docker.internal:host-gateway"

  server:
    image: one-server
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: one-server
    ports:
      - "${SERVER_PORT}:8000"
    volumes:
      - ../server/:/app/server/
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./logs:/var/lib/logs
    restart: on-failure
    networks:
      - one
    extra_hosts:
      - "host.docker.internal:host-gateway"
