services:
  redis:
    image: redis
    container_name: one-redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - one
    restart: on-failure
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data

networks:
  one:
    driver: bridge
