services:
  redis:
    image: redis
    container_name: one-redis
    ports:
      - "6379:6379"
    networks:
      - one
    restart: on-failure
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

networks:
  one:
    driver: bridge
