include:
  - ./docker-compose-base.yml

services:
  web:
    # build:
    #   context: ../web/ui
    #   dockerfile: Dockerfile
    image: one-ui
    container_name: one-ui
    ports:
      - "3333:3000"
    volumes:
      - ../web/ui/docker/pm2.json:/app/pm2.json
      - ../web/ui/docker/entrypoint.sh:/app/entrypoint.sh
    restart: on-failure
    networks:
      - one
    extra_hosts:
      - "host.docker.internal:host-gateway"

  server:
    # build:
    #   context: ../server
    #   dockerfile: Dockerfile
    image: one-server
    container_name: one-server
    ports:
      - "3334:3000"
    volumes:
      - ../server/:/app/server/
      - ./entrypoint.sh:/app/entrypoint.sh
    restart: on-failure
    networks:
      - one
    extra_hosts:
      - "host.docker.internal:host-gateway"
