name: Setup Poetry and Python

inputs:
  python-version:
    required: true
    default: 3.12

  poetry-version:
    required: true
    default: 1.8.4

runs:
  using: composite
  steps:
    - name: stepup python use ${{inputs.python-version}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{inputs.python-version}}
        cache: pip

    - name: install poetry
      shell: bash
      runs: pip install poetry==${{inputs.poetry-version}}
