name: 构建docker镜像
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: echo ${{github}}

      - uses: actions/checkout@v4

      - name: 登录至ghcr
        run: echo "${{ secrets.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 开始构建
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/one-server:latest

      - name: 推送
        run: docker push ghcr.io/${{ github.repository_owner }}/one-server:latest
