name: 构建 Docker 镜像
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [server, web]
    steps:
      - uses: actions/checkout@v4

      - name: 登录至 ghcr
        run: echo "${{ secrets.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 开始构建
        run: |
          if [[ "${{ matrix.service }}" == "server" ]]; then
            docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/one-server:latest
          elif [[ "${{ matrix.service }}" == "web" ]]; then
            cd web/ui
            docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/one-ui:latest
          fi

      - name: 推送
        run: |
          if [[ "${{ matrix.service }}" == "server" ]]; then
            docker push ghcr.io/${{ github.repository }}/one-server:latest
          elif [[ "${{ matrix.service }}" == "web" ]]; then
            docker push ghcr.io/${{ github.repository }}/one-ui:latest
          fi
