name: 打包前端部分
on: push
permissions:
  contents: write
jobs:
  build_ui:
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
      - name: 安装依赖
        run: |
          cd web/ui
          npm install 
          npx next build && npx next export
      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: web/ui/out
