on: push
jobs:
  build_ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls
      - run: cd web/ui
      - run: npm install
      - run: npm run build
