name: 测试Python环境
on:
  workflow_dispatch:

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: xxx
        uses: ./.github/actions/setup-poetry

      - run: pip list
