name: 测试Python环境
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: xxx
        uses: ./.github/actions/setup-poetry
        with:
          python-version: 3.12
          poetry-version: 1.8.4

      - run: pip list
